before_script:
  - echo -e "BRANCH/TAG => $CI_COMMIT_REF_NAME\nSLUG => $CI_COMMIT_REF_SLUG\nTITLE => $CI_COMMIT_TITLE\nSHA => $CI_COMMIT_SHA"

stages:
  - build
  - push
  - deploy

build_data:
  stage: build
  only:
    - develop
    - master
  script:
    - docker image build --pull . -f .nginx.Dockerfile -t registry.sfam.ovh/sfk/docker/$CI_PROJECT_NAME/nginx:$CI_COMMIT_REF_NAME
    - docker image build --pull . -f .php.Dockerfile -t registry.sfam.ovh/sfk/docker/$CI_PROJECT_NAME/php:$CI_COMMIT_REF_NAME
    # Push images in the registry
    - docker image push registry.sfam.ovh/sfk/docker/$CI_PROJECT_NAME/php:$CI_COMMIT_REF_NAME
    - docker image push registry.sfam.ovh/sfk/docker/$CI_PROJECT_NAME/nginx:$CI_COMMIT_REF_NAME

push_data:
  stage: push
  only:
    - develop
    - master
  script:
    - docker image push registry.sfam.ovh/sfk/apps/dolibarr/nginx:$CI_COMMIT_REF_NAME
    - docker image push registry.sfam.ovh/sfk/apps/dolibarr/php:$CI_COMMIT_REF_NAME

deploy_sandbox:
  stage: deploy
  only:
    - develop
  script:
    - ssh -T debian@c01d01.sfam.ovh "PROJECT=dolibarr IMAGE_TAG_PHP_CI=$CI_COMMIT_REF_NAME IMAGE_TAG_NGINX_CI=$CI_COMMIT_REF_NAME"

deploy_prod:
  stage: deploy
  only:
    - master
  script:
    - ssh -T debian@c01d01.sfam.ovh "PROJECT=dolibarr IMAGE_TAG_PHP_CI=$CI_COMMIT_REF_NAME IMAGE_TAG_NGINX_CI=$CI_COMMIT_REF_NAME"



